"""empty message

Revision ID: 0bf7832d16d0
Revises: 23f3039ba3dd
Create Date: 2023-05-20 00:41:54.615841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf7832d16d0'
down_revision = '23f3039ba3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carrito',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    op.create_table('Cliente',
    sa.Column('rut', sa.Integer(), nullable=False),
    sa.Column('tarjeta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rut')
    )
    op.create_table('Compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('transaccion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ProductoCarrito',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_carrito', 'id_producto')
    )
    op.create_table('Tarjeta',
    sa.Column('nro_tarjeta', sa.Integer(), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.Column('fecha_ven_dia', sa.Integer(), nullable=False),
    sa.Column('fecha_ven_año', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nro_tarjeta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tarjeta')
    op.drop_table('ProductoCarrito')
    op.drop_table('Compra')
    op.drop_table('Cliente')
    op.drop_table('Carrito')
    # ### end Alembic commands ###
