"""empty message

Revision ID: 603c8d7145d9
Revises: b5a6cf2c6687
Create Date: 2023-05-20 18:32:58.381167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603c8d7145d9'
down_revision = 'b5a6cf2c6687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductoCarrito', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductoCarrito', schema=None) as batch_op:
        batch_op.alter_column('id_producto',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
